build:
  version: "2.0"

external-api:
  message: "Welcome to BvrSoftware external-api related QA APIs "
  contactDetails:
    name: "Sanjeev Kumar - QA Lead"
    email: "sanjeev@bvrsoftware.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267