build:
  version: "1.0"

external-api:
  message: "Welcome to BvrSoftware external-api related prod APIs "
  contactDetails:
    name: "Sandra Harald - Product Owner"
    email: "sandra@bvrsoftware.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721