build:
  version: "3.0"

external-api:
  message: "Welcome to BvrSoftware external-api related local APIs "
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "dragos@bvrsoftware.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932