build:
  version: "2.0"

line-record-service:
  message: "Welcome to Bvr Software line-record-service related QA APIs "
  contactDetails:
    name: "Cyrano Marita - QA Lead"
    email: "cyrano@bvrsoftware.com"
  onCallSupport:
    - (785) 545-6565
    - (853) 546-3467