build:
  version: "3.0"

loans:
  message: "Welcome to Bvr Software line-record-service related local APIs "
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@bvrsoftware.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934