build:
  version: "2.0"

user-gate-way:
  message: "Welcome to Bvr Software user gate way related QA APIs "
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@bvrsoftware.com"
  onCallSupport:
    - (666) 265-3765
    - (666) 734-8371